# Generated by Django 5.1.6 on 2025-02-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_job_seeker',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employer', 'Роботодавець'), ('job_seeker', 'Шукач роботи')], default='job_seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
